services:
  mysql:
    container_name: mysql
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: 'yonothingtoseeheregoaway'
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
